# Base config for CE + Triplet with PK sampling
seed: 42
amp: true

# Data
data_root: /path/to/your_data_root
seq_len: 30
height: 64
width: 44
num_workers: 4

# Model
in_channels: 1
base_channels: 16
num_stripes: 8
embedding_dim: 256

# Train
epochs: 50
batch_p: 8
batch_k: 4
lr: 3e-4
weight_decay: 0.05
scheduler: cosine

# Logging & ckpt
out_dir: runs/lstc_metric
log_dir: runs/logs_metric
tensorboard: true
csv_log: true
resume: ""
