# Multi-view metric learning (CE + Triplet + MultiView PK)
seed: 42
amp: true

# Data
data_roots:
  - /path/to/view_0
  - /path/to/view_1
seq_len: 30
height: 64
width: 44
num_workers: 4

# Model
in_channels: 1
base_channels: 16
num_stripes: 8
embedding_dim: 256

# Train
epochs: 50
batch_p: 8
batch_k: 4
views_per_id: 2
balance_across_views: true
lr: 3e-4
weight_decay: 0.05
scheduler: cosine

# Logging & ckpt
out_dir: runs/lstc_metric_mv
log_dir: runs/logs_metric_mv
tensorboard: true
csv_log: true
resume: ""
