# OU-MVLP CE training (minimal)
seed: 42
amp: true

# Data
data_root: /path/to/OU-MVLP
views: ["000","015","030","045","060","075","090","180"]
seq_len: 30
height: 64
width: 44
num_workers: 4

# Model
in_channels: 1
base_channels: 16
num_stripes: 8
embedding_dim: 256

# Train
epochs: 50
batch_size: 64
lr: 3e-4
weight_decay: 0.05
scheduler: cosine

# Logging
out_dir: runs/ou_mvlp
log_dir: runs/logs_ou_mvlp
tensorboard: true
csv_log: true
