name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install PyTorch CPU
        run: |
          python -m pip install --upgrade pip
          pip install --index-url https://download.pytorch.org/whl/cpu \
            torch torchvision torchaudio

      - name: Install project deps
        run: |
          pip install -r requirements.txt --no-deps
          # tensorboard deps required by torch.utils.tensorboard
          pip install google protobuf absl-py werkzeug markdown antlr4-python3-runtime pyyaml
          pip install -e .
      - name: Import check
        run: |
          python - <<'PY'
import importlib
import sys
print('Python', sys.version)
importlib.import_module('lstc')
print('lstc imported OK')
PY
