name: Manual Sweep

on:
  workflow_dispatch:
    inputs:
      stripes:
        description: "Comma-separated stripes (e.g., 6,8)"
        required: false
        default: "6,8"
      topks:
        description: "Comma-separated top-k (e.g., 2,3)"
        required: false
        default: "2,3"
      modes:
        description: "Branch modes (tsj,t--,-s-,--j,ts-,t-j,-sj)"
        required: false
        default: "tsj,t--,-s-"

jobs:
  sweep:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyTorch CPU
        run: |
          python -m pip install --upgrade pip
          pip install --index-url https://download.pytorch.org/whl/cpu \
            torch torchvision torchaudio

      - name: Install project deps
        run: |
          pip install -r requirements.txt --no-deps
          pip install pyyaml antlr4-python3-runtime google protobuf absl-py werkzeug markdown

      - name: Generate toy dataset
        env:
          PYTHONPATH: .
        run: |
          python examples/gen_toy_dataset.py --out ./toy_data --subjects 4 --seq-per-subject 2 --frames 12

      - name: Run sweep (toy)
        env:
          PYTHONPATH: .
        run: |
          python examples/run_sweep.py \
            --data-root ./toy_data --seq-len 12 --epochs 2 --batch-size 8 \
            --device cpu --out runs/sweep \
            --stripes "${{ github.event.inputs.stripes || '6,8' }}" \
            --topks "${{ github.event.inputs.topks || '2,3' }}" \
            --modes "${{ github.event.inputs.modes || 'tsj,t--,-s-' }}"

      - name: Upload sweep artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sweep-results
          path: |
            runs/sweep/summary.csv
            runs/sweep/summary.md
